# Generated by Django 6.0.4 on 2026-05-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Заметка'),
        ),
    ]
